### ISSUE TITLE
exe problems

### ISSUE THREAD

**Issue by PiSaucer** [portablemc/portablemc#1]
Most computers now and days have .exe blocked. My school does not block .jar files because most of the time they are labs. I recommend that you also include [mineshafter](https://mineshafter.info/) in this program to allow more computers to work

**Comment by yeetedmeme** [comment]
my school has exe files blocked as well, if I provide the download as a zip file, then someone downloads and extracts the school software wont block it, or does the schools that you mentioned block the opening of .exe files?

**Comment by PiSaucer** [comment]
I can download zip files and extract them. The school stops exe or bat files from running. You can download it, no problem. Trying to run exe is the issue. I recommend mineshafter because it is jar file. My school doesn't block jar files because our labs are jar files.

**Comment by yeetedmeme** [comment]
il check it out, il leave this open till i find a conclusion

**Comment by yeetedmeme** [comment]
i assume your computers have java installed?

**Comment by yeetedmeme** [comment]
wait no, my bad this would be too much of a hassle to setup, in the near future i might find a way to turn it into a jar file, thanks anyways!

**Comment by yeetedmeme** [comment]
I decided to use mineshafter to make a release using .jar files, thanks!
