### ISSUE TITLE
Support forge?

### ISSUE THREAD

**Issue by PureNetProyect** [portablemc/portablemc#3]
i was using a exe version of a launcher and it don support forge.
does the exe version of this support forge?

**Comment by PureNetProyect** [comment]
I tried to launch it for using forge and the result is defender showing Trojan:Win32/Zpevdo.B

**Comment by yeetedmeme** [comment]
thanks, il look into it

**Comment by yeetedmeme** [comment]
its prolly your firewall, you would have to tweak settings there as windows really doesn't like forgian exe files without a certificate
